spring:
  database:
    username: postgres
    password: postgres
  mail:
    username: langen2023@gmail.com
    password: wnxchqguuinkzoqx
  email:
    classifications:
      tech: hughlujh2023@gmail.com
      general: general1@example.com
      support: support1@example.com