spring :
  profiles :
    active : dev
  config:
    import: application-secrets.yml
  datasource :
    hikari:
      auto-commit : true
    driver-class-name : org.postgresql.Driver
  jwt :
    token :
      secret-key : secret
  jpa :
    properties :
      hibernate :
        dialect : org.hibernate.dialect.PostgreSQLDialect
    show-sql : true
    generate-ddl : true
    hibernate :
      ddl-auto : update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  email:
    classifications:
      tech: ${email.classifications.tech}
      general: ${email.classifications.general}
      support: ${email.classifications.support}
